### ISSUE TITLE
Bad Practices

### ISSUE THREAD

**Issue by deluxejamie** [JarvoDiscord/Simple-v14-Discord.js-Bot#3]
You should not be redeploying commands on every restart of the bot, it's bad practices. Instead you could make a `deployer.js` file and an `npm deploy` script.

**Comment by JarvoDiscord** [comment]
@deluxejamie That's also a possible option, but it's not bad practice because you're redeploying the command for each startup 😂

In case you're renaming, or deleting commands, the bot would directly know that and update his command list. Even though there are no changes, the bot would still check on it to make sure it has the latest information from the commands.

Just because you know a other way to do it, doesn't mean it's the best way to do it 😉

**Comment by deluxejamie** [comment]
> @deluxejamie That's also a possible option, but it's not bad practice because you're redeploying the command for each startup 😂
> 
> In case you're renaming, or deleting commands, the bot would directly know that and update his command list. Even though there are no changes, the bot would still check on it to make sure it has the latest information from the commands.
> 
> Just because you know a other way to do it, doesn't mean it's the best way to do it 😉

It's not a good practice, you will be frequently sending unnecessary data to Discord.

**Comment by JarvoDiscord** [comment]
I use it at many bots. And they all work fine. That you want it to have it more difficult, then that is your choice. You're not sending useless data to Discord. You let Discord know that you updated your commands and that they need to change/replace/remove stuff, or do nothing.

Like I said, that you know a different way to do it, doesn't mean it's the best way to do it 😉
